- chainID: 43114
  rpcURL: http://127.0.0.1:9650/ext/bc/C/rpc
  startBlock: 1
  fetchBatchSize: 100
  maxConcurrency: 256
  name: C-Chain
  vm: evm

- chainID: 0
  rpcURL: http://127.0.0.1:9650
  startBlock: 1
  fetchBatchSize: 100
  maxConcurrency: 100
  name: P-Chain
  vm: p

